# Generated by Django 5.1 on 2024-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show_App', '0002_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
