# Generated by Django 5.1 on 2024-10-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show_App', '0004_show_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Show_App.user'),
        ),
    ]
