# Generated by Django 5.1 on 2024-10-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show_App', '0006_showcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shows', to='Show_App.user'),
        ),
    ]
