# Generated by Django 5.1 on 2024-10-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show_App', '0007_show_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='recommended_by',
        ),
    ]
